import type {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {ownedRouter,type UserLookup} from './owned';
export function learningSchema(db:DatabaseSync){db.exec(`
 CREATE TABLE IF NOT EXISTS annotations(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,material_id TEXT NOT NULL REFERENCES materials(id) ON DELETE CASCADE,page INTEGER NOT NULL,kind TEXT NOT NULL,text TEXT NOT NULL,comment TEXT NOT NULL,color TEXT NOT NULL,rects TEXT NOT NULL,points TEXT NOT NULL,created_at TEXT NOT NULL);
 CREATE INDEX IF NOT EXISTS annotations_owner ON annotations(user_id,material_id,page);
 CREATE TABLE IF NOT EXISTS vocabulary(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,course_id TEXT NOT NULL,word TEXT NOT NULL,meaning TEXT NOT NULL,example TEXT NOT NULL,pronunciation TEXT NOT NULL,source TEXT NOT NULL,card_id TEXT REFERENCES flashcards(id) ON DELETE SET NULL,created_at TEXT NOT NULL,FOREIGN KEY(course_id,user_id) REFERENCES courses(id,user_id) ON DELETE CASCADE);
 CREATE INDEX IF NOT EXISTS vocabulary_course ON vocabulary(user_id,course_id,created_at);
`);}
const coord=z.number().min(0).max(1),point=z.object({x:coord,y:coord}).strict();
const rect=point.extend({width:coord,height:coord}).refine(r=>r.x+r.width<=1.001&&r.y+r.height<=1.001);
const annotation=z.object({page:z.number().int().min(1).max(10000),kind:z.enum(['highlight','underline','bookmark','comment','drawing']),text:z.string().max(4000).default(''),comment:z.string().trim().max(4000).default(''),color:z.string().regex(/^#[a-f0-9]{6}$/i).default('#e9c846'),rects:z.array(rect).max(200).default([]),points:z.array(point).max(1500).default([])}).strict().refine(a=>a.kind==='drawing'?a.points.length>=2:a.kind==='highlight'||a.kind==='underline'?a.rects.length>0:a.kind==='comment'?a.comment.length>0:true);
const vocabulary=z.object({word:z.string().trim().min(1).max(300),meaning:z.string().trim().min(1).max(4000),example:z.string().max(4000).default(''),pronunciation:z.string().max(300).default(''),source:z.string().max(300).default('')}).strict();
export function learningRoutes(db:DatabaseSync,userFor:UserLookup,verified=false){const r=ownedRouter(db,userFor,verified);
 r.use('/materials/:id/annotations',(q,res,next)=>{const material=db.prepare('SELECT id,mime FROM materials WHERE id=? AND user_id=?').get(q.params.id,res.locals.userId);if(!material||material.mime!=='application/pdf'){res.status(404).json({error:'PDF not found.'});return;}next();});
 r.get('/materials/:id/annotations',(q,res)=>res.json(db.prepare('SELECT * FROM annotations WHERE material_id=? AND user_id=? ORDER BY page,created_at').all(q.params.id,res.locals.userId).map(a=>({...a,rects:JSON.parse(String(a.rects)),points:JSON.parse(String(a.points))}))));
 r.post('/materials/:id/annotations',(q,res)=>{const p=annotation.safeParse(q.body);if(!p.success){res.status(400).json({error:'Enter a valid annotation.'});return;}const count=db.prepare('SELECT COUNT(*) AS n FROM annotations WHERE material_id=? AND user_id=?').get(q.params.id,res.locals.userId)!;if(Number(count.n)>=2000){res.status(409).json({error:'This PDF has reached its annotation limit.'});return;}const id=randomUUID(),d=p.data;db.prepare('INSERT INTO annotations VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,res.locals.userId,q.params.id,d.page,d.kind,d.text,d.comment,d.color,JSON.stringify(d.rects),JSON.stringify(d.points),new Date().toISOString());res.status(201).json({id,...d});});
 r.delete('/annotations/:id',(q,res)=>{const d=db.prepare('DELETE FROM annotations WHERE id=? AND user_id=?').run(q.params.id,res.locals.userId);res.status(d.changes?204:404).send(d.changes?undefined:{error:'Annotation not found.'});});
 r.get('/courses/:id/vocabulary',(_q,res)=>res.json(db.prepare('SELECT * FROM vocabulary WHERE course_id=? AND user_id=? ORDER BY created_at DESC').all(res.locals.courseId,res.locals.userId)));
 r.post('/courses/:id/vocabulary',(q,res)=>{const p=vocabulary.safeParse(q.body);if(!p.success){res.status(400).json({error:'Enter a word and its meaning.'});return;}const id=randomUUID(),d=p.data;db.prepare('INSERT INTO vocabulary VALUES(?,?,?,?,?,?,?,?,NULL,?)').run(id,res.locals.userId,res.locals.courseId,d.word,d.meaning,d.example,d.pronunciation,d.source,new Date().toISOString());res.status(201).json({id,...d,card_id:null});});
 r.delete('/vocabulary/:id',(q,res)=>{const d=db.prepare('DELETE FROM vocabulary WHERE id=? AND user_id=?').run(q.params.id,res.locals.userId);res.status(d.changes?204:404).send(d.changes?undefined:{error:'Vocabulary item not found.'});});
 r.post('/vocabulary/:id/flashcard',(q,res)=>{const v=db.prepare('SELECT * FROM vocabulary WHERE id=? AND user_id=?').get(q.params.id,res.locals.userId);if(!v){res.status(404).json({error:'Vocabulary item not found.'});return;}if(v.card_id){res.json({id:v.card_id});return;}const id=randomUUID();db.exec('BEGIN');try{let deck=db.prepare("SELECT id FROM flashcard_decks WHERE user_id=? AND course_id=? AND name='Vocabulary'").get(res.locals.userId,v.course_id);if(!deck){deck={id:randomUUID()};db.prepare('INSERT INTO flashcard_decks VALUES(?,?,?,?)').run(deck.id,res.locals.userId,v.course_id,'Vocabulary');}db.prepare('INSERT INTO flashcards(id,deck_id,front,back,topic,source) VALUES(?,?,?,?,?,?)').run(id,deck.id,v.word,[v.meaning,v.example,v.pronunciation].filter(Boolean).join('\n'),'Vocabulary',v.source);db.prepare('UPDATE vocabulary SET card_id=? WHERE id=?').run(id,v.id);db.exec('COMMIT');res.status(201).json({id});}catch(e){db.exec('ROLLBACK');throw e;}});
 return r;}
